/*
* PAQUETE GENERADO PARA CREAR PRUEBAS Y SUBIR ARCHIVOS
* (CLASES, METODOS ALGORITMOS EN FASE DE PRUEBA) QUE TAL VEZ NO FUNCIONEN
* PERO SE NECESITA SUBIR EL AVANCE MOMENTANEAMENTE EN ESTE PAQUETE SE SUBE
* CUALQUIER COSA(VISTAS, CONTROLADORES O MODELOS), NO DEBE AFECTAR LOS DEMAS
* PAQUETES.
* ESTE PAQUETE SERA ELIMINADO CUANDO SE TERMINE LA APLICACION.
*/
package com.mx.sief.test;

/**
 * @author Francisco Juárez
 * 
 */
public class LoginTest {
    
}
